### ISSUE TITLE
Fix Clipboard Saving for Chrome on Mac

### ISSUE THREAD

**Issue by ehraiford** [SWIM-ucf/SWIM#223]

**Comment by b0x-Cub3d** [comment]
Update on this issue, https://github.com/jetli/yew-hooks/issues/28#issuecomment-1633028979

We should test it out like this, and if it still doesn't work then we have to accept that limitation.

**Comment by b0x-Cub3d** [comment]
It turns out this only happens on Macs that utilize Apple Silicon since Intel Macs aren't affected. The fix for this bug is to program the clipboard event in a way that guarantees the write to the clipboard vs. some underlying conditional within the WASM binary. Yes, that means we probably have to debug the compiled WASM bytecode ;)
